"""empty message

Revision ID: fcce7e1c3692
Revises: e7f2fa3a78a5
Create Date: 2023-01-20 14:23:24.373810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcce7e1c3692'
down_revision = 'e7f2fa3a78a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_lower', sa.String(length=255), nullable=False),
    sa.Column('forum_url', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=False),
    sa.Column('file_count', sa.BIGINT(), nullable=False),
    sa.Column('downloads', sa.BIGINT(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('approved_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('mods_count', sa.BIGINT(), nullable=True),
    sa.Column('mods_url', sa.String(length=255), nullable=True),
    sa.Column('collections', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('new_mods',
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('mod_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('allow_rating', sa.Boolean(), nullable=False),
    sa.Column('domain_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('endorsement_count', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('created_time', sa.String(length=255), nullable=False),
    sa.Column('updated_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('uploaded_users_profile_url', sa.String(), nullable=False),
    sa.Column('contains_adult_content', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('member_group_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('endorsement', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('mod_id')
    )
    op.create_table('trending_mods',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('picture_url', sa.String(length=255), nullable=True),
    sa.Column('mod_downloads', sa.BigInteger(), nullable=True),
    sa.Column('mod_unique_downloads', sa.BigInteger(), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('mod_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('allow_ratings', sa.Boolean(), nullable=True),
    sa.Column('domain_name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('endorsement_count', sa.Integer(), nullable=True),
    sa.Column('created_timestamp', sa.String(length=255), nullable=True),
    sa.Column('updated_timestamp', sa.String(length=255), nullable=True),
    sa.Column('updated_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_user_profile_url', sa.String(length=255), nullable=True),
    sa.Column('contains_adult_content', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('user_member_id', sa.BigInteger(), nullable=True),
    sa.Column('user_member_group_id', sa.BigInteger(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('endorsement', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trending_mods')
    op.drop_table('new_mods')
    op.drop_table('games')
    # ### end Alembic commands ###
